//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationAthleticsCompetitions.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganizationAthleticsCompetitionsEntities1 : DbContext
    {
        public OrganizationAthleticsCompetitionsEntities1()
            : base("name=OrganizationAthleticsCompetitionsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryCompetition> CategoryCompetition { get; set; }
        public virtual DbSet<CategorySportsman> CategorySportsman { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<FormatResult> FormatResult { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeProgram> TypeProgram { get; set; }
        public virtual DbSet<Venue> Venue { get; set; }
        public virtual DbSet<Trainer_Team> Trainer_Team { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<ResultCompetition> ResultCompetition { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<ProgramCompetition> ProgramCompetition { get; set; }
        public virtual DbSet<TypeCompetition> TypeCompetition { get; set; }
        public virtual DbSet<Sportsman> Sportsman { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
