//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationAthleticsCompetitions.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorTeam
    {
        public int Id { get; set; }
        public Nullable<int> IdSponsor { get; set; }
        public Nullable<int> IdTeam { get; set; }
        public Nullable<int> IdTrainer { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> DateOfChange { get; set; }
        public string VisibilityCansel => IdStatus == 1 ? "Visible" : "Collapsed";
        public virtual Sponsor Sponsor { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
