//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationAthleticsCompetitions.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Team
    {
        public int IdTrainer { get; set; }
        public int IdTeam { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual Team Team { get; set; }
    }
}
