//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationAthleticsCompetitions.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCompetition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeCompetition()
        {
            this.ProgramCompetition = new HashSet<ProgramCompetition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdFormatResult { get; set; }
        public Nullable<double> Distance { get; set; }
        public string Gender { get; set; }
    
        public virtual FormatResult FormatResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramCompetition> ProgramCompetition { get; set; }
    }
}
