//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationAthleticsCompetitions.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Trainer = new HashSet<Trainer>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Заполните ФИО!")]
        public string FullName { get; set; }

        public Nullable<int> IdCity { get; set; }

        [Required(ErrorMessage = "Заполните логин!")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Заполните пароль!")]
        public string Password { get; set; }
        public Nullable<int> IdRole { get; set; }
        public Nullable<System.DateTime> DayOfBirth { get; set; }
    
        public virtual City City { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainer> Trainer { get; set; }
    }
}
